// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test', async function() {
    await driver.get("http://localhost:3000/?name=Merwan&email=djdjdjdj%40ddhdhdh")
    await driver.manage().window().setRect({ width: 550, height: 692 })
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("dfdfdfdfd")
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("dfdfdfd@ggggg")
    await driver.findElement(By.css("input:nth-child(1)")).click()
  })
})
